version: "3"
services:
  mariadb-database:
    container_name: mariadb-database
    image: mariadb/server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mariadb_test
      MYSQL_USER: bharath
      MYSQL_PASSWORD: password
    ports: 
      - 3306:3306

  zookeeper:
    container_name: zookeeper
    image:  wurstmeister/zookeeper:3.4.6
    expose: 
      - "2181"
    restart: always
  
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9093:9093"
    environment: 
      KAFKA_CREATE_TOPICS: "mariadb-events:1:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on: 
      - zookeeper
    expose: 
      - "9092"

  mariadb-service-app:
    container_name: mariadb-service-app
    image: bharathkuppala/gomariadb-service-app
    # build:
    #   context : .
    #   dockerfile: Dockerfile.dev
    ports: 
      - 8080:8080
    depends_on:
      - mariadb-database
      - kafka
    restart: always




  





